### ISSUE TITLE
The openweather layout is inconsistent.

### ISSUE THREAD

**Issue by gesangtome** [jenslody/gnome-shell-extension-openweather#166] opened 2016-11-28 11:00 UTC
System version: fedora23-workstation
Gnome version: 3.18.2
Language: Chinese
  Hello ,I’m very fond of the openweather. But,There is a layout problem, On the top right-hand corner of the panel, 4 labels and numerical position is not aligned, Can you fix this?
![default](https://cloud.githubusercontent.com/assets/9876749/20666966/e11c96ae-b5a1-11e6-9311-6571fd4ae0d0.JPG)

**Comment by jenslody** [comment] 2016-11-28 11:38
Duplicate of #160

**Closed by jenslody** 2016-11-28 11:38 UTC
