### ISSUE TITLE
Add yr.no as datasource

### ISSUE THREAD

**Issue by HeikoAdams** [jenslody/gnome-shell-extension-openweather#135] opened 2016-08-14 18:45 UTC
Yr.no is the free online service of the norwegian meteorological institute (met.no) and provides free weather data too. IMHO these data is more reliable then forecast.io or openweathermap

**Comment by jenslody** [comment] 2016-08-14 20:49
Duplicate of #70 
No fix for this until now, if you (or somebody else) know(s) a free javascript xml-parsing library, that can be used from a gnome-shell-extension, I will add yr.no as weather-provider.

**Closed by jenslody** 2016-08-14 20:49 UTC
Labels: duplicate
