### ISSUE TITLE
Incorrect weather information shown.

### ISSUE THREAD

**Issue by ssameer** [jenslody/gnome-shell-extension-openweather#118] opened 2016-02-24 17:01 UTC
The weather data displayed from the panel doesn't match the weather data on openweathermap.org website. The website shows correct information (especially temperature), when you click on the "Weather data provided by ..." link in the panel popup. The location shown in the panel popup is correct.

https://openweathermap.org/city/5393212

Gnome 3.16, 3.18 on Ubuntu 15.10. Extension installed from extensions.gnome.org

**Comment by jenslody** [comment] 2016-02-24 20:09
I also saw the difference, but at the moment, both show the same.
Anyway, it's an issue on openweathermap.org site, if the values from the website and returned by their api differ.
That's the url I use to fetch the current weather, so you can test it yourself:
http://api.openweathermap.org/data/2.5/weather?lat=34.0195598&lon=-118.4869738&units=metric&APPID=c93b4a667c8c9d1d1eb941621f899bb8 (metric)
If you want other temperature-formats:
http://api.openweathermap.org/data/2.5/weather?lat=34.0195598&lon=-118.4869738&units=imperial&APPID=c93b4a667c8c9d1d1eb941621f899bb8 (imperial)
or
http://api.openweathermap.org/data/2.5/weather?lat=34.0195598&lon=-118.4869738&APPID=c93b4a667c8c9d1d1eb941621f899bb8 (standard, temperature in Kelvin)

I close this, because it's not a bug with the extension, but probably an issue (or a temporary hickup) on the weather-providers site, so I can not do anything, sorry.

Jens

**Closed by jenslody** 2016-02-24 20:09 UTC
