### ISSUE TITLE
Causes entire gnome environment to hang when there is no connection

### ISSUE THREAD

**Issue by keaneokelley** [jenslody/gnome-shell-extension-openweather#95] opened 2015-11-16 17:49 UTC
Nov 16 08:58:33 <user> gnome-session[6036]: Gjs-Message: JS LOG: Can not connect to     https://openweathermap.org/city/0?APPID=efc65750f4e3d5f9d0ba43ad94b
    Nov 16 08:58:33 <user> gnome-session[6036]: Error resolving 'openweathermap.org': Name or service not known

Whenever I change WiFi networks or bring my VPN up/down, the entire gnome-shell hangs anywhere from 20 seconds to 2 minutes. The system is unusable- the mouse moves but the windows are completely unresponsive. The hang is only limited to gnome; I can still switch to a pty and work there. However, it makes my system unusable.

Why do I blame openweather? When the extension is enabled, I get the long hang. When it's disabled, I have no issues at all. You can see in the journalctl output above that that openweather is complaining. This shows up about once per second. 

If you need any more information, let me know. I know this seems vague or unrelated, but it is definitely causing my issue.

**Comment by jenslody** [comment] 2015-11-16 19:48
This is a duplicate of #82 and fixed in master, on extensions.gnome.org and on Fedora (update-testing).

**Closed by jenslody** 2015-11-16 19:48 UTC
Labels: duplicate

**Comment by jenslody** [comment] 2015-11-16 22:59
By the way: I just removed your personal api-key from your comment.
You should not share it and you do not need it with the newest version of the extension.
