### ISSUE TITLE
Doesn't find any location

### ISSUE THREAD

**Issue by v1c3** [jenslody/gnome-shell-extension-openweather#74] opened 2015-09-17 22:04 UTC
Seems openweathermap.org search engine is broken (on their homepage)

Search on forecast.io works, but not in your addon

**Comment by jenslody** [comment] 2015-09-18 08:24
Please have a look at https://extensions.gnome.org/extension/750/openweather/ for the cause of the issue.
Nevertheless it's fixed in git, on gnome.org and in my fedora-repo.

**Closed by jenslody** 2015-09-18 08:24 UTC
