### ISSUE TITLE
Support for Weather Underground.

### ISSUE THREAD

**Issue by cdysthe** [jenslody/gnome-shell-extension-openweather#167] opened 2016-12-08 19:17 UTC
Hi,

Would it be possible to get support for the Weather Underground API (with key) in this extension? There's a weather indicator available for Ubuntu Unity with Weather Underground support, but I can't find one for GNOME.

**Comment by jenslody** [comment] 2016-12-10 10:33
Duplicate of #64.
I will ad an answer there.

**Closed by jenslody** 2016-12-10 10:33 UTC
